### PR TITLE
Python fixes

### PR DESCRIPTION
**Pull request by markushx**
Support python3 with count.py example and align stdout flushing in count.py with the behaviour of the count.sh.

Additionally, the Python example on the frontpage of http://websocketd.com/ needs an update. Since there is no flushing of stdout, the example only outputs at the end when the script finishes. Doesn't seem to be a github page, so no patch.

### CODE REVIEW

**Comment by asergeyev** [comment]
Thanks, moving sleep is a good fix

**Comment by asergeyev** [comment]
But speaking about python3... Since examples are so simple, any chance you could help to make others both 2 (at least with __future__) and 3 compatible?

**Comment by asergeyev** [comment]
to be followed up in #112

**Comment by joewalnes** [comment]
The frontpage is in the gh-pages branch (index.html). You can send a pull req.

**Comment by markushx** [comment]
The only thing necessary for 3 compatibility is brackets for print() according to 2to3:
```
mab:python mab$ 2to3 dump-env.py 
RefactoringTool: Skipping implicit fixer: buffer
RefactoringTool: Skipping implicit fixer: idioms
RefactoringTool: Skipping implicit fixer: set_literal
RefactoringTool: Skipping implicit fixer: ws_comma
RefactoringTool: Refactored dump-env.py
--- dump-env.py	(original)
+++ dump-env.py	(refactored)
@@ -34,11 +34,11 @@
   'HTTPS'
 ]
 for var_name in var_names:
-  print '%s=%s' % (var_name, os.environ.get(var_name, '<unset>'))
+  print('%s=%s' % (var_name, os.environ.get(var_name, '<unset>')))
   stdout.flush() # Remember to flush
 
 # Additional HTTP headers
 for var_name in os.environ:
   if var_name.startswith('HTTP_'):
-    print '%s=%s' % (var_name, os.environ[var_name])
+    print('%s=%s' % (var_name, os.environ[var_name]))
     stdout.flush() # Remember to flush
RefactoringTool: Files that need to be modified:
RefactoringTool: dump-env.py
```

```
mab:python mab$ 2to3 greeter.py 
RefactoringTool: Skipping implicit fixer: buffer
RefactoringTool: Skipping implicit fixer: idioms
RefactoringTool: Skipping implicit fixer: set_literal
RefactoringTool: Skipping implicit fixer: ws_comma
RefactoringTool: Refactored greeter.py
--- greeter.py	(original)
+++ greeter.py	(refactored)
@@ -10,5 +10,5 @@
 # For each line FOO received on STDIN, respond with "Hello FOO!".
 while True:
   line = stdin.readline().strip()
-  print 'Hello %s!' % line
+  print('Hello %s!' % line)
   stdout.flush() # Remember to flush
RefactoringTool: Files that need to be modified:
RefactoringTool: greeter.py
```

**Comment by asergeyev** [comment]
Interesting... I thought "" % ""  would not work in 3 and apparently it's fine there.

**Comment by asergeyev** [comment]
Will take care of those.

**Pull request merged**
