### PR TITLE
Adding Java example

### PR DESCRIPTION
**Pull request by schrepfler**

### CODE REVIEW

**Comment by schrepfler** [comment]
Hm, the rendering is not good on chrome, perhaps there's no support for java in the code syntax library?

**Comment by asergeyev** [comment]
still looking there...

**Comment by schrepfler** [comment]
Prism.js does list java as supported language.http://prismjs.com/#languages-list

**Comment by asergeyev** [comment]
will fix... needs new lang added

**Comment by asergeyev** [comment]
Works now.

**Comment by schrepfler** [comment]
(ok)

**Pull request merged**
