### PR TITLE
Gorilla support in Websocketd

### PR DESCRIPTION
**Pull request by asergeyev**
Ok, let's face it I don't have time to do big rewrite right now... But this sounds doable to reuse most of our code with gorilla...

Any takers to build/try to use it? Or people would prefer pre-released binaries?

### CODE REVIEW

**Comment by asergeyev** [comment]
I wonder if you have any comments, @joewalnes

**Comment by asergeyev** [comment]
Currently it seem not working under Windows 10. Will investigate further (not even listening to socket so it's quite deep inside of go basic network operations)

**Comment by joewalnes** [comment]
👍 LGTM so far

**Comment by asergeyev** [comment]
Added how windows is treated and rebased so it's annoying a bit how things re-committed but it would work.

**Pull request merged**
