### PR TITLE
added quickjs example

### PR DESCRIPTION
**Pull request by coderofsalvation**

### CODE REVIEW

**Comment by asergeyev** [comment]
I'm bit confused because bigger part of this code UTF conversion.... Anyone experienced in qjs can review/comment?

**Comment by coderofsalvation** [comment]
quickjs's stdin internal format is an utf8buffer (=array).
To eventually send it out, a conversion to a string is needed.

**Comment by ctn-malone** [comment]
While the code in this PR is the way to go to convert bytes array to utf8, if you use `std.in.getline()` instead of `std.in.getByte()`, there should be no need for any conversion

```
import * as std from 'std';
import * as os from 'os';

let line;
while ((line = std.in.getline()) != null) {
    console.log(line);
    std.out.flush();
}
```

Of course it assumes that input from client will be line oriented, which is a safe assumption imho

**Comment by coderofsalvation** [comment]
thanks..that looks much better. 
I've updated the pullrequest @asergeyev can you merge?

**Review by asergeyev — APPROVED** [review]
Looks good, thanks

**Pull request merged**
