### PR TITLE
supported broadcast for specify script

### PR DESCRIPTION
**Pull request by yzprofile**
I know there were lots of issues of `broadcast`

like: 
https://github.com/joewalnes/websocketd/issues/133
https://github.com/joewalnes/websocketd/issues/95
https://github.com/joewalnes/websocketd/issues/50
https://github.com/joewalnes/websocketd/pull/237

so, I did this if it helpful.

### CODE REVIEW

**Comment by asergeyev** [comment]
Well this would be open (for few weeks likely) for people interested in broadcasting websocket server topic. My concerns are mostly around input flow and breaking xinetd/inetd model.  As we said earlier, concept of broadcasting creates completely different tool than websocketd... but let's talk about it.

**Comment by yzprofile** [comment]
For the broadcast script we can config it self, and do not accept any input from client.

It just broadcast what server push.

we can also make more config option for each script if we want. I think it's more flexible.

**Comment by asergeyev** [comment]
I'll pass. Config hooks really don't fit well into simple model that websocketd provides. Will close after a while, leaving time for discussion to see if users would still like this to be merged

**Comment by yzprofile** [comment]
that's ok.

That's patch we used in our own production with [jsmpeg](https://github.com/phoboslab/jsmpeg) for broadcasting h264 stream.

**Pull request closed without merging**
