### PR TITLE
Added Nim versions

### PR DESCRIPTION
**Pull request by rapind**

### CODE REVIEW

**Comment by asergeyev** [comment]
What are pros and cons to have all possible languages to be in examples folder of websocketd?
Should we go wild here or have some nominal screening rules?

**Comment by rapind** [comment]
Not sure I see any cons, but if you do add screening, I recommend Nim as an increasingly popular general purpose systems language and a very reasonable backend for web sockets.

**Comment by rapind** [comment]
I added a simple voting version for kicks that just increments a key in a redis backend. I thought it might be useful to hook up a simple backend to ballpark the memory that would be consumed per process and get an idea of the number of concurrents that could be supported. IMO it's a pretty small footprint and could support a decent number of concurrents (assuming memory is the bottleneck), like 5k+ on a $20 / month VPS.

screen shot 2015-02-16 at 10 38 15 am

**Comment by asergeyev** [comment]
IMO this illustrates nim and not websocketd. Also since both Ubuntu and Fedora do not have nim in their default repositories (correct me please if I'm wrong) it's questionable that the language is so popular that missing example written in it would hurt potential users.

How about you will build this voter app somewhere in github and we'll refer to it in wiki?

**Comment by rapind** [comment]
@asergeyev yes I agree the voter piece belongs elsewhere. I justed wanted a feel for the efficiency or lack of efficiency in using a websocketd (process per) approach for high traffic.

I do however think a Nim example is more meaningful than a vbscript one :). I'll tear the voter piece out of my fork in case you change your mind about merging the counter / greeter examples.

**Comment by asergeyev** [comment]
Do you think we can get back to this after Nim is stabilized to 1.0 version? Do you know there are plans of that in community?

**Comment by rapind** [comment]
Of course, let's revisit after 1.0. I think the plan is still for 1.0 to hit early this year (I.e. soonTM). See https://github.com/Araq/Nim/wiki/Roadmap for more detail.

**Comment by asergeyev** [comment]
Cool and thanks!

**Pull request closed without merging**
